services:
  - type: web
    name: TomatoBotDocker
    env: docker
    repo: https://github.com/zahid718865/Tomato
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
